import Head from 'next/head'
import Link from 'next/link'
import Footer from './footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex items-center justify-between p-4 bg-slate-500 text-gray-50'>
        <h1>Cookie Stand</h1>
        <p></p>
      </header>
      <main className=''>

      </main>
      <Footer></Footer>
    </>
  )
}
